server:
  port: 0

spring:
  application:
    name: 1st-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    # ??? ???? ??? ?????? ????? ??
    fetch-registry: true
    # ??? ??? ??? ????? ??
    register-with-eureka: true
    service-url:
      # ??? ??? ?? url ??
      defaultZone: http://localhost:8761/eureka