### 문자열 응답
GET http://localhost:8080/response/hello


### 객체 응답
GET http://localhost:8080/response/message


### 리스트 응답
GET http://localhost:8080/response/list


### Map 응답
GET http://localhost:8080/response/map


### image 응답
GET http://localhost:8080/response/image


### entity 응답
GET http://localhost:8080/response/entity