### user 목록 조회
GET http://localhost:8080/entity/users

### 특정 user 조회
GET http://localhost:8080/entity/users/1

### 신규 user 등록
POST http://localhost:8080/entity/users
Content-Type: application/json

{
  "id" :"user04",
  "pwd" : "pass04",
  "name" : "신사임당"
}

### 기존 user 수정
PUT http://localhost:8080/entity/users/1
Content-Type: application/json

{
  "pwd" : "pass0101",
  "name" : "홍길동동동"
}

### 특정 user 삭제
DELETE http://localhost:8080/entity/users/2