spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
#      jdbc-url: jdbc:mariadb://localhost:3306/menudb
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
      username: swcamp
      password: swcamp
logging:
  level:
    com:
      ohgiraffers:
        section01:
          factorybean: debug
