# Docker Compose 파일의 버전을 정의한다. 최신 기능과 호환성을 결정한다.
version: '3'
services:
  backend:
    # 해당 디렉토리의 Dockerfile을 사용해 이미지를 빌드
    build: ./chap01_01_bootProject
    # 컨테이너 이름을 'backend'로 설정
    container_name: backend
    # 호스트의 8080 포트를 컨테이너의 8080 포트로 매핑
    ports:
      - "8080:8080"

  frontend:
    # 해당 디렉토리의 Dockerfile을 사용해 이미지를 빌드
    build: ./chap01_02_vueProject
    # 컨테이너 이름을 'frontend'로 설정
    container_name: frontend
    # 호스트의 5173 포트를 컨테이너의 8080 포트로 매핑
    ports:
      - "5173:5173"