spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  packages-to-scan: com.ohgiraffers
  default-consumes-media-type: application/json;charset=UTF-8 # -- ?? Content-Type ??
  default-produces-media-type: application/json;charset=UTF-8 # -- ?? Content-Type ??
  swagger-ui:
    path: /swagger

token:
  secret: jcbbmpPbq7gw8TC1n6vCcAAgNTCQtZVHhRkSOTSuM5iYi6RmW1g/8h9rYkL7OQq/MZZ08cambRHW5O6dQ1p0PQ==
  expiration_time: 43200000